# language type:
language: cpp

# compilator system:
compiler:
  - clang
  - gcc

os:
  - linux
  - osx

# previous actions:
before_script: 
  - cd ..
  - git clone https://github.com/HeeroYui/etk.git
  - git clone https://github.com/HeeroYui/gtest.git
  - pwd
  - ls -l
  - if [ "$CXX" == "clang++" ]; then BUILDER=clang; else BUILDER=gcc; fi

#install Gcc to have lisstdc++ 4.9 & gcc 4.9
install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -qq
  - sudo apt-get install -qq g++-4.9
  - sudo apt-get install -qq libstdc++-4.9-dev
  - sudo rm /usr/bin/gcc /usr/bin/g++
  - sudo ln -s /usr/bin/gcc-4.9 /usr/bin/gcc
  - sudo ln -s /usr/bin/g++-4.9 /usr/bin/g++
  - sudo pip install lutin

# build sequence with Lutin :
script: 
  - lutin -C -P -c$BUILDER -mdebug -p exml_test
  - ./out/Linux_x86_64/debug/staging/$BUILDER/exml_test/usr/bin/exml_test -l6

#send e-mail on compilation result:
notifications:
  email:
    - yui.heero@gmail.com

