language:
  - cpp

sudo: false

compiler:
  - clang
  - gcc

os:
  - linux
  - osx

branches:
  only:
    - master
    - dev

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.9

install:
  - pip install --user lutin
  - wget http://atria-soft.com/coverage/sendCoverage.py .

before_script:
  - cd ..
  - git clone https://github.com/atria-soft/etk.git
  - git clone https://github.com/generic-library/gtest-lutin.git --recursive
  - pwd
  - ls -l
  - if [ "$CXX" == "clang++" ]; then BUILDER=clang; else BUILDER=gcc; fi
  - if [ "$CXX" == "g++" ]; then COMPILATOR_OPTION="--compilator-version=4.9"; else COMPILATOR_OPTION=""; fi

script:
  - if [ "$CXX" == "clang++" ]; then lutin -C -P -c$BUILDER $COMPILATOR_OPTION -mdebug -p exml-test; fi
  - if [ "$CXX" == "clang++" ]; then ./out/Linux_x86_64/debug/staging/$BUILDER/exml-test/usr/bin/exml-test -l6; fi
  - if [ "$CXX" == "g++" ]; then lutin -C -P -c$BUILDER $COMPILATOR_OPTION --gcov -mdebug -p exml-test; fi
  - if [ "$CXX" == "g++" ]; then ./out/Linux_x86_64/debug/staging/$BUILDER/exml-test/usr/bin/exml-test -l6; fi
  - if [ "$CXX" == "g++" ]; then lutin -C -P -c$BUILDER $COMPILATOR_OPTION --gcov -mdebug -p exml?gcov -l6; fi
  - if [ "$CXX" == "g++" ]; then ./sendCoverage.py "http://atria-soft.com/coverage/inject.php" "atria-soft" "XXX" "exml" "master" "out/Linux_x86_64/debug/build/gcc/exml/exml_coverage.json"; fi

notifications:
  email:
    - yui.heero@gmail.com

